ekf_filter_node:
  ros__parameters:
  


  # Si 



  
    frequency: 30.0 
    two_d_mode: true 		#  x,y,yaw
    publish_tf: true            #  odom → base_link
    
    transform_tolerance: 0.1

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /demo/odom
    odom0_config: [ true,  true,  false,   # x     y      z
                    false, false, false,   # roll  pitch  yaw
                    true,  false, false,   # vx    vy     vz
                    false, false, false,   # vroll vpitch vyaw
                    false, false, false ]  # ax    ay     az
                    
    odom0_queue_size: 5
    odom0_differential: false
    odom0_relative: false

    imu0: /demo/imu
    imu0_config:  [ false, false, false,   # x y z (IMU no da posición)
                    false, false, true,    # solo yaw
                    false, false, false,   # vx vy vz
                    true,  true,  true,    # tasas angulares (wx, wy, wz)
                    false, false, false ]  # aceleraciones (por ahora off)
                    
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: false
